#theme: minima
theme: cayman
name: "Bilal Ismail"
title: "Bilal Ismail"
author: "bait"
description: "You can ask me about cybersecurity and software engineering."
include: ["_pages"]
baseurl: /
url: https://bilal-ismail.github.io

