theme: minima
#remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

name: "Bilal Ismail"
title: "Bilal Ismail"
author: "bait"
description: "You can ask me about cybersecurity and software engineering."
include: ["_pages"]
baseurl: /
url: https://bilal-ismail.github.io/about
