theme: minima
#remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

name: "Bilal Ismail"
title: "Bilal Ismail"
author: "Lean adoption and continuos learning practitioner"
description: "You can ask me about cloud, cybersecurity and software engineering."
include: ["_pages"]
exclude: ["_posts"]
baseurl: /
url: https://bilal-ismail.github.io
